### ISSUE TITLE
Error messages should end with a newline

### ISSUE THREAD

**Issue by pvgoran** [sago35/Getopt-Kingpin#33]
Normally, human-readable command output is newline-terminated. Kingpin's error messages are not. Popular shells don't take it very well: `bash` shows its prompt after the non-terminated line, and zsh (version 5.4.2 in Nixos) somehow "eats" the non-terminated line, thus hiding the error message completely.

**Comment by pvgoran** [comment]
How about publishing a new version with the correction of this problem?

**Comment by sago35** [comment]
@pvgoran 
I'm sorry, I forgot.
I just released 0.08 of Getopt::Kingpin.

https://metacpan.org/release/TAKASAGO/Getopt-Kingpin-0.08

Me and my workplace still use Getopt::Kingpin.
Maintenance is still planned to continue.

**Comment by pvgoran** [comment]
@sago35 Thank you!
