### ISSUE TITLE
`parse` should really take an arrayref

### ISSUE THREAD

**Issue by tobyink** [sago35/Getopt-Kingpin#36]
`$kingpin->parse` parses `@ARGV` but `$kingpin->parse(@args)` parses `@args`... except if `@args` is an empty array, in which case it parses `@ARGV` even though that's not what you asked it to do.

If `parse` took an arrayref, then it would be easier for `parse` to tell if you wanted it to parse your array or parse `@ARGV`.

```perl
$kingpin->parse( \@args ); # parse @args 
$kingpin->parse( [] );     # parse an empty array
$kingpin->parse;           # parse @ARGV 
```

But Getopt::Kingpin has already existed for four years, so it is probably too late to change the behaviour of `parse`. Instead I think a separate method called `parse_array` should be added and `parse` should be... not quite deprecated but discouraged.

**Comment by sago35** [comment]
You are right.
But it's certainly hard to change `parse()` now.

**Comment by sago35** [comment]
Thank you.
