### ISSUE TITLE
Hash-typed flags

### ISSUE THREAD

**Issue by tobyink** [sago35/Getopt-Kingpin#37]
For arguments like this:

    myscript.pl command --define os=linux --define arch=amd64

And `$flag->values` should return:

    {
      "os" => "linux",
      "arch" => "amb64",
    }

Getopt::Long supports this. If you think this would be a useful feature, I would be happy to send you a patch.

**Comment by sago35** [comment]
@tobyink I think it's a very useful feature.
It would be very nice if you make a PR.
