### ISSUE TITLE
Lazy defaults

### ISSUE THREAD

**Issue by tobyink** [sago35/Getopt-Kingpin#43]
For me, it would be useful if Getopt::Kingpin supported "lazy" defaults like Moo/Moose attributes do. So, for example:

```perl
$command->flag("email", "Email address")->default(sub { ... })->string;
```

Looking up the email address might be an expensive operation; it might need a database lookup for example. The coderef would only be called if the user does not provide `--email=something` on the command line.

It would allow things like:

```perl
$command->flag("email", "Email address")->default(sub {
  print STDERR "Please provide an email address!\n";
  chomp( my $email = <STDIN> );
  return $email;
})->string;
```

I can provide a PR if you think this is a useful feature which you would be likely to accept.

**Comment by sago35** [comment]
@tobyink 
I think it's a very good feature.
Please send the PR.
